'use strict';
(() => {
 const $=id=>document.getElementById(id), API=(window.SPORTS_CONFIG?.API_BASE||'').replace(/\/$/,'');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=n=>Number(n).toLocaleString('zh-TW',{maximumFractionDigits:1});
 const date=s=>new Date(s).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'});
 let key='',records=[],types=[];
 async function load() {try {const r=await fetch(API+'/api/teacher/records',{headers:{Authorization:'Bearer '+key}});const data=await r.json();if(!r.ok)throw Error(data.error||'無法讀取');records=data.records;types=data.types;$('loginPanel').hidden=true;$('dashboard').hidden=false;const previous=$('classFilter').value;const classes=[...new Set(records.map(r=>r.student.className))].sort();$('classFilter').innerHTML='<option value="">全部班級</option>'+classes.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(classes.includes(previous))$('classFilter').value=previous;$('dataTime').textContent='更新於 '+date(new Date());render();}catch(e){$('loginPanel').hidden=false;$('dashboard').hidden=true;$('loginStatus').textContent=e.message==='Failed to fetch'?'成績服務目前無法連線，請確認主機已啟動。':e.message;}}
 function filtered() {const p=$('paperFilter').value,c=$('classFilter').value;return records.filter(r=>(!p||r.paperId===p)&&(!c||r.student.className===c));}
 function summarize(rows) {const map=new Map();for(const r of [...rows].sort((a,b)=>new Date(a.receivedAt)-new Date(b.receivedAt))){const id=r.student.className+'|'+r.student.seatNumber;let s=map.get(id);if(!s){s={...r.student,count:0,first:r.score,best:r.score,last:r.score,time:r.receivedAt};map.set(id,s);}s.count++;s.best=Math.max(s.best,r.score);s.last=r.score;s.time=r.receivedAt;s.studentName=r.student.studentName;}return [...map.values()].sort((a,b)=>a.className.localeCompare(b.className)||Number(a.seatNumber)-Number(b.seatNumber));}
 function roster() {const value=$('rosterInput').value;try {localStorage.setItem('sports115-teacher-roster',value);}catch{}if(!$('classFilter').value){$('missingSeats').textContent='請先選擇一個班級。';return;}const seats=new Set();for(const part of value.split(/[,、\s]+/)){if(/^\d{1,3}$/.test(part))seats.add(Number(part));else if(/^\d{1,3}-\d{1,3}$/.test(part)){const [a,b]=part.split('-').map(Number);if(a<=b&&b-a<=200)for(let i=a;i<=b;i++)seats.add(i);}}const submitted=new Set(filtered().map(r=>Number(r.student.seatNumber)));const missing=[...seats].filter(s=>!submitted.has(s)).sort((a,b)=>a-b);$('missingSeats').textContent=!seats.size?'請填入應交座號。':missing.length?`尚未交卷：${missing.join('、')} 號`:'名單中的學生都已交卷。';}
 function render() {const rows=filtered(),students=summarize(rows),average=f=>students.length?students.reduce((s,r)=>s+r[f],0)/students.length:0;$('stats').innerHTML=[['完成人數',students.length],['交卷次數',rows.length],['首次平均',fmt(average('first'))],['最佳平均',fmt(average('best'))]].map(([name,value])=>`<div class="stat-card"><strong>${value}</strong><span>${name}</span></div>`).join('');$('studentRows').innerHTML=students.map(s=>`<tr><td>${esc(s.className)}</td><td>${esc(s.seatNumber)}</td><td>${esc(s.studentName)}</td><td>${s.count}</td><td>${fmt(s.first)}</td><td>${fmt(s.best)}</td><td>${fmt(s.last)}</td><td>${esc(date(s.time))}</td></tr>`).join('');$('emptyRecords').hidden=!!rows.length;const totals=new Map(types.map(t=>[t.id,{...t,total:0,wrong:0}]));for(const r of rows)for(const item of r.items){const t=totals.get(item.typeId);t.total++;if(!item.full)t.wrong++;}$('typeBars').innerHTML=[...totals.values()].sort((a,b)=>(b.total?b.wrong/b.total:0)-(a.total?a.wrong/a.total:0)).map(t=>`<div class="type-bar"><div class="progress-label"><span>${t.id}. ${esc(t.title)}</span><span>${t.wrong} / ${t.total} 次${t.total?'・'+Math.round(t.wrong/t.total*100)+'%':''}</span></div><div class="progress-track"><div class="bar" style="width:${t.total?t.wrong/t.total*100:0}%"></div></div></div>`).join('');$('attemptRows').innerHTML=rows.slice(0,50).map(r=>`<details class="record"><summary>${esc(r.student.className)} ${esc(r.student.seatNumber)} 號 ${esc(r.student.studentName)}・卷 ${r.paperId}・${fmt(r.score)} 分・${esc(date(r.receivedAt))}</summary><p>作答完成：${esc(date(r.finishedAt))}；服務收到：${esc(date(r.receivedAt))}</p><div class="table-wrap"><table><thead><tr><th>題號</th><th>題型</th><th>作答</th><th>得分</th></tr></thead><tbody>${r.items.map(i=>`<tr><td>${i.number}</td><td>${esc(types.find(t=>t.id===i.typeId)?.title)}</td><td>${esc(i.selected||'未作答')}</td><td>${fmt(i.points)} / 4</td></tr>`).join('')}</tbody></table></div></details>`).join('')||'<p class="empty">還沒有交卷紀錄。</p>';roster();}
 function csv() {const rows=filtered();const escape=v=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const data=[['班級','座號','姓名','練習卷','分數','未得滿分題號','完成時間','服務收到時間'],...rows.map(r=>[r.student.className,r.student.seatNumber,r.student.studentName,r.paperId,r.score,r.items.filter(i=>!i.full).map(i=>i.number).join('、'),date(r.finishedAt),date(r.receivedAt)])];const url=URL.createObjectURL(new Blob(['\uFEFF'+data.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='高一體育班段考練習-成績.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 $('paperFilter').innerHTML+=[...'ABCDEFGHIJ'].map(p=>`<option value="${p}">練習卷 ${p}</option>`).join('');$('loginForm').addEventListener('submit',e=>{e.preventDefault();key=$('teacherKey').value.trim();$('teacherKey').value='';load();});$('refresh').addEventListener('click',load);$('export').addEventListener('click',csv);$('paperFilter').addEventListener('change',render);$('classFilter').addEventListener('change',render);$('rosterInput').addEventListener('input',roster);try {$('rosterInput').value=localStorage.getItem('sports115-teacher-roster')||'';}catch{}
 if(['127.0.0.1','localhost'].includes(location.hostname))fetch('/api/teacher/local-session').then(r=>r.ok?r.json():Promise.reject()).then(data=>{key=data.key;load();}).catch(()=>{$('loginStatus').textContent='請確認本機成績服務已啟動。';});
})();
